### ISSUE TITLE
Association navigability

### ISSUE THREAD

**Issue by Hartorn** [thc-tools/model-schemas#4]
Association should have some way to define navigability, like an actor can get the movies he played in, but maybe you don't want to get all movies when getting a kind.

It may be defined as true all, none, or as an array of string like 'idA->idB' maybe.

Not sure this is the best way, but definitely useful

**Comment by bushi-go** [comment]
Might be a bi tricky to define, but i agree it will be definetily usefull. However we will need to define precisely how we will ensure the unique identification of our entities before we can efficiently implement such feature

**Comment by Hartorn** [comment]
Yep, agreed
